jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github Action test"

        - name: list files
          run: 'ls -ltr'

        - name: Read file
          run: cat README.md